from tkinter import *

main = Tk()
main.geometry("1300x700")
main.title("School Nutritionist")
main.configure(bg='#ebf5fb')
main.resizable(False,False)
heading = Label(main,text="NUTRITION MANAGEMENT",bg="#D35400",fg="white", font = ("Arial",30))
heading.pack(fill=BOTH,padx=20,pady=10)
style = ("Calibri", 22)
mainframe = Frame(main, bg = '#d2fc82', width = 1000, height = 580)
mainframe.pack(fill = BOTH, padx=20,pady=20)
age_options = ["Primary","Secondary","Teacher"]
clicked = StringVar()
roti = StringVar()
clicked.set(age_options[0])
age_grp = OptionMenu(mainframe, clicked, *age_options)
age_grp.place(x=480,y=490)
age_grp.configure(bg='red',fg='white')
submitbtn = Button(mainframe, text = "Submit",width = 12,font=style,bg='#7FB3D5')
submitbtn.place(x=800,y=470)
Label(mainframe, text = 'Enter average daily consumption',width = 78,font=style).place(x=40,y=30)
Label(mainframe,bg='#F1948A', text = "Chapatis(no.)", width = 20,font = style).place(x=50,y=120)
Label(mainframe,bg='#F1948A', text = "Legumes(in g)", width = 20,font = style).place(x=50,y=190)
Label(mainframe,bg='#F1948A', text = "Cooked Beans(in g)", width = 20,font = style).place(x=50,y=260)
Label(mainframe,bg='#F1948A', text = "Fish(in g)", width = 20,font = style).place(x=50,y=330)
Label(mainframe,bg='#F1948A', text = "Chicken(no.)", width = 20,font = style).place(x=50,y=400)
Label(mainframe,bg='#F1948A', text = "", width = 20,font = style).place(x=670,y=120)
Label(mainframe,bg='#F1948A', text = "", width = 20,font = style).place(x=670,y=190)
Label(mainframe,bg='#F1948A', text = "", width = 20,font = style).place(x=670,y=260)
Label(mainframe,bg='#F1948A', text = "", width = 20,font = style).place(x=670,y=330)
Label(mainframe,bg='#F1948A', text = "", width = 20,font = style).place(x=670,y=400)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=400,y=120)
legume_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); legume_txt.place(x=400,y=190)
bean_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); bean_txt.place(x=400,y=260)
fish_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); fish_txt.place(x=400,y=330)
chicken_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); chicken_txt.place(x=400,y=400)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=1020,y=120)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=1020,y=190)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=1020,y=260)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=1020,y=330)
roti_txt = Entry(mainframe,textvariable = roti,bg='#82E0AA', width = 12,font = style); roti_txt.place(x=1020,y=400)
Label(mainframe,text = "Select\nAge group",font=style).place(x=300,y=470)




main.mainloop()
