from tkinter import *
import mysql.connector

def food_intake():
        uid = 'pulkit69'
        apple = apple_entry.get()
        print(apple)
        orange = orange_entry.get()
        spinach = spinach_entry.get()
        legume = legume_entry.get()
        peas = peas_entry.get()
        milk = milk_entry.get()
        yogurt = yogurt_entry.get()
        eggs = eggs_entry.get()
        fish = fish_entry.get()
        chicken = chicken_entry.get()
        exe = mysql.connector.connect(user= 'root',host='localhost',database='schoolnutritionist',password='tiger')
        cur=exe.cursor()
        query1 = '''select * from common_food'''
        query2 = '''insert into patient_intake values("{}",{},{},{},{},{},{},{},{},{},{})'''.format(uid,apple,orange,spinach,legume,peas,milk,\
                                                                                                    yogurt,eggs,fish,chicken)
        cur.execute(query1)
        nutrivalues_main = cur.fetchall()
        cur.execute(query2)
        cur.execute('commit')
        print(nutrivalues_main)


main = Tk()
main.geometry("1300x700")
main.title("School Nutritionist")
main.configure(bg='#ebf5fb')
main.resizable(False,False)
heading = Label(main,text="NUTRITION MANAGEMENT",bg="#D35400",fg="white", font = ("Arial",30))
heading.pack(fill=BOTH,padx=20,pady=10)
style = ("Calibri", 22)
mainframe = Frame(main, bg = '#d2fc82', width = 1000, height = 580)
mainframe.pack(fill = BOTH, padx=20,pady=20)
age_options = ["Primary","Secondary","Teacher"]
clicked = StringVar()
apple = DoubleVar(); orange = DoubleVar(); spinach = DoubleVar(); legume = DoubleVar(); peas = DoubleVar()
milk = DoubleVar(); yogurt = DoubleVar(); eggs = DoubleVar(); fish = DoubleVar(); chicken = DoubleVar()
clicked.set(age_options[0])
age_grp = OptionMenu(mainframe, clicked, *age_options)
age_grp.place(x=480,y=490)
age_grp.configure(bg='red',fg='white')

Label(mainframe, text = 'Enter average daily consumption',width = 78,font=style).place(x=40,y=30)
Label(mainframe,bg='#F1948A', text = "Apple(no.)", width = 20,font = style).place(x=50,y=120)
Label(mainframe,bg='#F1948A', text = "Oranges(no.)", width = 20,font = style).place(x=50,y=190)
Label(mainframe,bg='#F1948A', text = "Spinach(in g)", width = 20,font = style).place(x=50,y=260)
Label(mainframe,bg='#F1948A', text = "Legumes(in g)", width = 20,font = style).place(x=50,y=330)
Label(mainframe,bg='#F1948A', text = "Green peas(in g)", width = 20,font = style).place(x=50,y=400)
Label(mainframe,bg='#F1948A', text = "Milk(no.of cups)", width = 20,font = style).place(x=670,y=120)
Label(mainframe,bg='#F1948A', text = "Yogurt(no.of cups)", width = 20,font = style).place(x=670,y=190)
Label(mainframe,bg='#F1948A', text = "Eggs(no.)", width = 20,font = style).place(x=670,y=260)
Label(mainframe,bg='#F1948A', text = "Fish(in g)", width = 20,font = style).place(x=670,y=330)
Label(mainframe,bg='#F1948A', text = "Chicken(in g)", width = 20,font = style).place(x=670,y=400)

apple_entry = Entry(mainframe,bg='#82E0AA', width = 12,font = style)
apple_entry.place(x=400,y=120)
orange_entry = Entry(mainframe,textvariable = orange,bg='#82E0AA', width = 12,font = style)
orange_entry.place(x=400,y=190)
spinach_entry = Entry(mainframe,textvariable = spinach,bg='#82E0AA', width = 12,font = style)
spinach_entry.place(x=400,y=260)
legume_entry = Entry(mainframe,textvariable = legume,bg='#82E0AA', width = 12,font = style)
legume_entry.place(x=400,y=330)

peas_entry = Entry(mainframe,textvariable = peas,bg='#82E0AA', width = 12,font = style)
peas_entry.place(x=400,y=400)
milk_entry = Entry(mainframe,textvariable = milk,bg='#82E0AA', width = 12,font = style)
milk_entry.place(x=1020,y=120)
yogurt_entry= Entry(mainframe,textvariable = yogurt,bg='#82E0AA', width = 12,font = style)
yogurt_entry.place(x=1020,y=190)
eggs_entry = Entry(mainframe,textvariable = eggs,bg='#82E0AA', width = 12,font = style)
eggs_entry.place(x=1020,y=260)
fish_entry = Entry(mainframe,textvariable = fish,bg='#82E0AA', width = 12,font = style)
fish_entry.place(x=1020,y=330)
chicken_entry = Entry(mainframe,textvariable = chicken,bg='#82E0AA', width = 12,font = style)
chicken_entry.place(x=1020,y=400)
Label(mainframe,text = "Select\nAge group",font=style).place(x=300,y=470)
submitbtn = Button(mainframe, text = "Submit",width = 12,font=style,bg='#7FB3D5',command=food_intake)
submitbtn.place(x=800,y=470)

main.mainloop()

